### PR TITLE
Fix incorrect favorite states in search results

### LINKED ISSUE #189: 收藏状态显示错误
### 复现步骤 / Step to reproduce

1. 收藏某艺术家的一或多个画廊。
2. 打开所有带有该艺术家标签的搜索。

录屏: https://fars.ee/qmCZ.mp4

### 预期行为 / Expected behaviour

仅在已收藏的画廊显示心图标。

### 实际行为 / Actual Behaviour

在已收藏的画廊往下每隔8个画廊就会再次出现假的心图标（并没有收藏该画廊），进入一次这种出现这种心图标的画廊再返回，假的心图标就不会出现。

此时，再访问一次有真的心图标的画廊再返回，每隔8个画廊出现的假的心图标又回来了。

### 应用日志 / App logs

[logcat-2023-11-02-21-47-38-039.txt](https://github.com/FooIbar/EhViewer/files/13239524/logcat-2023-11-02-21-47-38-039.txt)

### 备注 / Addition details

_No response_

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

b273f10

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

Google Pixel 5

### SoC 型号 / Soc model

Snapdragon 765G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #189

### CODE REVIEW

File: app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt [hunk 1]
```diff
@@ -120,13 +122,9 @@ fun GalleryInfoListItem(
...
                         },
                     ) {
-                        val download by produceState(false, info.gid) {
-                            // Workaround ComposeView in RecyclerView, since view is reused, remembered value will not update when setContent with similar @Composable lambda, since composer group key is the same
-                            value = DownloadManager.containDownloadInfo(info.gid)
-                            DownloadManager.stateFlow(info.gid).collect {
-                                value = DownloadManager.containDownloadInfo(info.gid)
-                            }
-                        }
+                        val download by remember {
```
Comment (nullArrayList) [inline app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt:125]: remember should use a gid key

**Review by nullArrayList — APPROVED** [review]
