### PR TITLE
Animate comments update, Resolve #450

### LINKED ISSUE #450: The State of Comment not be Updated Properly
### 复现步骤 / Step to reproduce

1. Vote any comment
2. Exit to gallery
3. Reopen the comment

### 预期行为 / Expected behaviour

The point of comment after voting should be remembered.

### 实际行为 / Actual Behaviour

It is not remembered.

https://github.com/FooIbar/EhViewer/assets/62805286/53895343-18d1-4cfe-89bf-f39b6a5ded25

### 应用日志 / App logs

Irelevant

### 备注 / Addition details

The point of comment after voting should be stored locally if the voting has succeeded. But if we exit the comment area, the state will be lost. It may WAI but may not work as intuitive.

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

95ccabc

### Android 系统版本 / Android version

MIUI 14

### 设备型号 / Device model

Xiaomi 12S Pro

### SoC 型号 / Soc model

Snapdragon 8+ Gen 1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by VDostoyevskiy**

### CODE REVIEW

**Review by FooIbar — APPROVED** [review]

File: app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt [hunk 1]
```diff
@@ -174,6 +173,9 @@ fun GalleryCommentsScreen(galleryDetail: GalleryDetail, navigator: DestinationsN
         val url = EhUrl.getGalleryDetailUrl(galleryDetail.gid, galleryDetail.token, 0, showAll)
         val detail = EhEngine.getGalleryDetail(url)
         comments = detail.comments
+
+        // Refresh comments of GalleryDetail cache
+        galleryDetail.comments = comments
```
Comment (FooIbar) [inline app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt:178]: How can this solve the issue?
It's the same as https://github.com/FooIbar/EhViewer/blob/d880b30ea92822b446800dbe89acc1ce72b2e75d/app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt#L164-L166
