### PR TITLE
Use Downloads as start screen if device is offline

### LINKED ISSUE #1672: 增加一个【启动页设为下载】的功能
### 复现步骤 / Step to reproduce

设置➡️eh➡️启动页

### 预期行为 / Expected behaviour

有主页、订阅、热门、排行、下载

### 实际行为 / Actual Behaviour

有主页、订阅、热门、排行

### 应用日志 / App logs

none

### 备注 / Addition details

有此功能就便于在飞机上看本了

按模板填写后不知道怎么改label，不好意思

### 浏览站点 / Browsing site

none

### EhViewer 版本号 / EhViewer version code

1.13.0 snapshot 

### EhViewer CI 版本 / EhViewer CI Version

ae3a669

### Android 系统版本 / Android version

澎湃os 1.0.18.0

### 设备型号 / Device model

红米k70

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #1672

### CODE REVIEW

File: app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt [hunk 1]
```diff
@@ -466,9 +472,16 @@ class MainActivity : EhActivity() {
                             // https://issuetracker.google.com/336140982
                             // SharedTransitionLayout {
                             CompositionLocalProvider(LocalSharedTransitionScope provides NoopSharedTransitionScope) {
+                                val start = if (Settings.needSignIn) {
```
Comment (revonateB0T) [inline app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt:475]: Use when expression instead.

**Review by revonateB0T — APPROVED** [review]
