### PR TITLE
Fix preload in reader

### LINKED ISSUE #1510: 阅读器翻页时会出现非常短暂的白屏加载，即使所浏览的画廊已经被完全下载
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/5458ed4e-5cb0-4003-a5f9-68caef90c59b

这个录屏可以看到，最开始从1到5页浏览，翻页时都会短暂白屏闪一下，仔细看能看到加载动画的那个圈，但是再从5翻回1页这个难受的白屏快闪就没了，即便再从1翻到5页，但从5页翻到9页这个闪屏又有了，后面的就是相同的情况复现。

### 预期行为 / Expected behaviour

对于已经下载/预载好的画页，阅读器翻页时不应该出现白屏加载，而且还是非常短暂地出现，在快速翻页阅览的时候这个快闪白屏会让眼睛非常疲劳。

### 实际行为 / Actual Behaviour

即使是在线浏览的画廊，对于已经预载的画页也会这样，之前老版的阅读器是没有这个情况的，我记得之前用的CI版本有可以在设置里开关那个被标注为[WIP]的阅读器，我启用那个阅读器就会有相同的情况，关掉后就没有了，现在看来那个阅读器应该是转正了，不过这个问题却一直遗留了下来。

### 应用日志 / App logs

[log-2024-08-11-19-35-38-541.zip](https://github.com/user-attachments/files/16573525/log-2024-08-11-19-35-38-541.zip)

### 备注 / Addition details

我是使用的手机音量键进行翻页操作的，在屏幕上翻页不会有这个问题（可能是因为有页面过渡动画？），并且这个时候再用音量键翻页也看不到加载动画的那个圈了，但是白屏快闪的问题依旧存在。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-snapshot

### EhViewer CI 版本 / EhViewer CI Version

78a237f

### Android 系统版本 / Android version

HyperOS 1.0.18.0

### 设备型号 / Device model

Redmi K70 Pro

### SoC 型号 / Soc model

8g3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #1510

### CODE REVIEW

File: app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt [hunk 1]
```diff
@@ -161,7 +165,17 @@ class ArchivePageLoader(
         false
     }
 
-    override fun preloadPages(pages: List<Int>, pair: Pair<Int, Int>) {}
+    override fun preloadPages(pages: List<Int>, bounds: Pair<Int, Int>) {
```
Comment (revonateB0T) [inline app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: Does preload pages for Archive actually make sense?
We preload pages just for reduce time user wait for network request, but decode is fast and mostly costs less than 1 seconds, should we waste CPU decoding an image may not be shown?

Comment (revonateB0T) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: I do think the preload mechanism of LazyList is enough, if we ought to preload it ourselves, we must decay preload range then.

Comment (FooIbar) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: Well, sort of. Decompression may take a measurable time depending on the format.
And we scroll 0.75 * viewport height at a time, so a few pages need to be preloaded to avoid loading while scrolling.

Comment (revonateB0T) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: Meanwhile, unlike network request, both decompress & decode is **not** cancellable, I feel like there will be something wrong during fast scroll across pages.

Comment (revonateB0T) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: I think we could hardcode preload range to +-2 pages given user have normal read speed.

Comment (FooIbar) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: For pager modes, even ±1 would be enough.
For webtoon modes, it becomes a little complicated as we don't know 0.75 * viewport height = how many pages.

Comment (FooIbar) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: For a 20:9 screen, 20 / 9 * 0.75 / 1.4125 ≈ 1.2.
So we'll need to preload 2 pages at times (when more than 0.8 of the next page is in screen).
And we need to consider 16:9 CGs, 20 / 9 * 0.75 * 16 / 9 ≈ 3.

Comment (revonateB0T) [reply app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt:168]: > For a 20:9 screen, 20 / 9 * 0.75 / 1.4125 ≈ 1.2. So we'll need to preload 2 pages at times (when more than 0.8 of the next page is in screen). And we need to consider 16:9 CGs, 20 / 9 * 0.75 * 16 / 9 ≈ 3.

Then let's hardcode range to 3, just not let it reach maximum 17

**Review by revonateB0T — APPROVED** [review]
