### PR TITLE
Handle invalid UTF-8 characters in response body

### LINKED ISSUE #643: 响应正文含有无效 UTF-8 字符导致解码失败
### 复现步骤 / Step to reproduce

访问特定画廊 https://e-hentai.org/g/1241525/7eb4b2e1ea

### 预期行为 / Expected behaviour

正常显示

### 实际行为 / Actual Behaviour

报错“Input length = 1”

Screenshot_2024-01-19-17-10-46-79_f2f1746601bf3b868d00d5efaf12e601

### 应用日志 / App logs

[log-2024-01-19-17-10-52-341.zip](https://github.com/FooIbar/EhViewer/files/13986915/log-2024-01-19-17-10-52-341.zip)

### 备注 / Addition details

_No response_

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

a37cc59

### Android 系统版本 / Android version

ColorOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #643

### CODE REVIEW

File: app/src/main/kotlin/com/hippo/ehviewer/util/KtorExtensions.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package com.hippo.ehviewer.util
+
+import io.ktor.client.call.body
+import io.ktor.client.statement.HttpResponse
+import io.ktor.utils.io.charsets.decode
+import io.ktor.utils.io.core.ByteReadPacket
+import java.nio.charset.CodingErrorAction
+
+suspend fun HttpResponse.bodyAsUtf8Text(): String {
+    val decoder = Charsets.UTF_8.newDecoder().apply {
```
Comment (VDostoyevskiy) [inline app/src/main/kotlin/com/hippo/ehviewer/util/KtorExtensions.kt:10]: Is `CharsetDecoder` thread safe?
Consider make it a top-level val or `ThreadLocal`

File: app/src/main/rust/src/lib.rs [hunk 2]
```diff
@@ -79,13 +78,13 @@ where
     R: Serialize,
 {
     let buffer = deref_mut_direct_bytebuffer(env, str);
-    let html = unsafe { from_utf8_unchecked(&buffer[..limit as usize]) };
-    let value = match tl::parse(html, tl::ParserOptions::default()) {
-        Ok(dom) => match f(&dom, html) {
+    let html = String::from_utf8_lossy(&buffer[..limit as usize]);
```
Comment (VDostoyevskiy) [inline app/src/main/rust/src/lib.rs:81]: I don't think we have to check it in advance since this have unnecessary overhead.
tl takes str as bytes, and use `from_utf8_lossy` internally when we request inner text of some tags.

Comment (FooIbar) [reply app/src/main/rust/src/lib.rs]: Done.

**Review by VDostoyevskiy — APPROVED** [review]
